module.exports = {
  // compare
  ifEmpty: ['@pdg/compare', 'ifEmpty'],
  ifNotEmpty: ['@pdg/compare', 'ifNotEmpty'],
  isEmpty: ['@pdg/compare', 'isEmpty'],
  isNotEmpty: ['@pdg/compare', 'isNotEmpty'],
  empty: ['@pdg/compare', 'empty'],
  notEmpty: ['@pdg/compare', 'notEmpty'],
  ifNotNull: ['@pdg/compare', 'ifNotNull'],
  ifNull: ['@pdg/compare', 'ifNull'],
  isNotNull: ['@pdg/compare', 'isNotNull'],
  isNull: ['@pdg/compare', 'isNull'],
  ifNotUndefined: ['@pdg/compare', 'ifNotUndefined'],
  ifUndefined: ['@pdg/compare', 'ifUndefined'],
  isNotUndefined: ['@pdg/compare', 'isNotUndefined'],
  isUndefined: ['@pdg/compare', 'isUndefined'],
  ifNotNullAndUndefined: ['@pdg/compare', 'ifNotNullAndUndefined'],
  ifNullOrUndefined: ['@pdg/compare', 'ifNullOrUndefined'],
  isNotNullAndUndefined: ['@pdg/compare', 'isNotNullAndUndefined'],
  isNullOrUndefined: ['@pdg/compare', 'isNullOrUndefined'],
  isContains: ['@pdg/compare', 'isContains'],
  contains: ['@pdg/compare', 'contains'],
  isEqual: ['@pdg/compare', 'isEqual'],
  equal: ['@pdg/compare', 'equal'],
  isBusinessNo: ['@pdg/compare', 'isBusinessNo'],
  isEmail: ['@pdg/compare', 'isEmail'],
  isInteger: ['@pdg/compare', 'isInteger'],
  isMobileNo: ['@pdg/compare', 'isMobileNo'],
  isNumericText: ['@pdg/compare', 'isNumericText'],
  isPersonalNo: ['@pdg/compare', 'isPersonalNo'],
  isTelNo: ['@pdg/compare', 'isTelNo'],
  isUrl: ['@pdg/compare', 'isUrl'],

  // date-time
  beginDateOfDay: ['@pdg/date-time', 'beginDateOfDay'],
  beginDateOfMonth: ['@pdg/date-time', 'beginDateOfMonth'],
  endDateOfDay: ['@pdg/date-time', 'endDateOfDay'],
  endDateOfMonth: ['@pdg/date-time', 'endDateOfMonth'],
  extractDate: ['@pdg/date-time', 'extractDate'],
  now: ['@pdg/date-time', 'now'],
  nowJs: ['@pdg/date-time', 'nowJs'],
  nowTime: ['@pdg/date-time', 'nowTime'],
  weekdayText: ['@pdg/date-time', 'weekdayText'],

  // data
  lv: ['@pdg/data', 'lv'],
  vl: ['@pdg/data', 'vl'],
  copy: ['@pdg/data', 'copy'],

  // react-hook
  useChanged: ['@pdg/react-hook', 'useChanged'],
  useFirstSkipChanged: ['@pdg/react-hook', 'useFirstSkipChanged'],
  useEventEffect: ['@pdg/react-hook', 'useEventEffect'],
  useEventLayoutEffect: ['@pdg/react-hook', 'useEventLayoutEffect'],
  useFirstSkipEffect: ['@pdg/react-hook', 'useFirstSkipEffect'],
  useFirstSkipLayoutEffect: ['@pdg/react-hook', 'useFirstSkipLayoutEffect'],
  useForwardRef: ['@pdg/react-hook', 'useForwardRef'],
  useMountedRef: ['@pdg/react-hook', 'useMountedRef'],
  useAutoUpdateRef: ['@pdg/react-hook', 'useAutoUpdateRef'],
  useTimeoutRef: ['@pdg/react-hook', 'useTimeoutRef'],
  clearTimeoutRef: ['@pdg/react-hook', 'clearTimeoutRef'],
  useIntervalRef: ['@pdg/react-hook', 'useIntervalRef'],
  clearIntervalRef: ['@pdg/react-hook', 'clearIntervalRef'],
};
